### PR TITLE
Add `get_readable_bytes_count()` function

### PR DESCRIPTION
**Pull request by yakov-bakhmatov**
To read an unknown number of bytes from a serial port without a timeout, you need a function that returns the number of bytes received by the serial port. This pull request adds that function.

Exadmple:
```
const BUF_LEN: usize = 100;
let mut buf = [0u8; BUF_LEN];
let readable = port.get_readable_bytes_count().unwrap();
if readable > 0 {
    let len = port.read(&mut buf[0..std::cmp::min(readable, BUF_LEN)]).unwrap();
}
```

Tested on Windows 7 and Ubuntu 17.10.

### CODE REVIEW

**Comment by apelican** [comment]
I'd like to see this approved!
I am considering this library to use rust in porting a set of Obj-C daemons that sit forever on an RS-232 connection and generate real-time events, so this scenario seems like a valid one for a serial library.

**Comment by dcuddeback** [comment]
@yakov-bakhmatov I don't think feature this is something I want to maintain, because:

1. I'm not convinced it's necessary. If I understand what you're trying to accomplish, you can get the same thing with `poll()`/`select()`/`kqueue()`. And even searching the internet for information on the ioctl that you're using (`FIONREAD`), I see people say "just use `select` instead."
2. It can be implemented out-of-crate, since the raw file descriptor and handle are exposed. If only a handful of people need a feature, I think that's better done out-of-crate than bringing it internal to the crate.
3. I don't know how portable it will be. You say you tested on Windows and Ubuntu, but I also support macOS, *BSD, and in the future probably embedded.

I think what you're missing is here: 

```rust
let len = port.read(&mut buf[0..std::cmp::min(readable, BUF_LEN)]).unwrap();
```

The `min()` call is unnecessary, because `read()` returns as soon as any data is available. It doesn't block until `BUF_LEN` bytes are read. So you're really just using `readable` as a flag for when data is available. That's what `poll()`/`select()`/`kqueue()` are for.

**Comment by yakov-bakhmatov** [comment]
@dcuddeback, you are right, this feature is not needed for `unix` implementation.
But, unfortunately, reading on `windows` is blocked until all requested bytes are read or a timeout occurs:

[Serial Communications](https://msdn.microsoft.com/ru-ru/library/ff802693.aspx)

> ## Communications Time-outs

> Nonoverlapped operations will block until all the requested bytes are transferred. The `ReadFile` function is blocked until all the requested characters arrive at the port.

Therefore, I propose to change the implementation of `COMPort::read()` as follows:

https://github.com/yakov-bakhmatov/serial-rs/commit/b8500ab3fd7de98e021b2c1071c344942e634d46

**Comment by araffin** [comment]
This feature seems quite useful for me too (I'm currently working on serial communication with arduino and one of the thread blocked the other because no bytes were available).
If you don't want to integrate it in the crate, I would grateful if you could provide link/example to do it outside of the lib ;)

To give more context: https://github.com/araffin/rust-arduino-serial/blob/master/examples/arduino_threads.rs
I'm using two threads: one is listening to the Arduino, the other is sending messages to it
For now, the listener thread wait a bit when a timeout error is raised, because not bytes where available. That allows the command thread to acquire the lock on the serial.

**Comment by dcuddeback** [comment]
@yakov-bakhmatov

> reading on windows is blocked until all requested bytes are read or a timeout occurs

I don't see why that's a problem. You can set a short timeout, and you get whatever bytes are available. See also the MSDN docs for serial timeouts: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddser/ns-ntddser-_serial_timeouts.

> If ReadIntervalTimeout is set to MAXULONG, and both ReadTotalTimeoutConstant and ReadTotalTimeoutMultiplier are zero, a read request completes immediately with the bytes that have already been received, even if no bytes have been received. In this case, the read request returns the STATUS_SUCCESS status code.

Maybe that's what you're asking for? Honestly, it's still not very clear to me what you're trying to solve for or how the code behaves differently from expectations. I think this discussion would be better as a bug report with some details.

Anyways, I'm going to close this PR since I'm not merging `get_readable_bytes_count()`. Feel free to file a bug report with some details, including a minimal reproduction example (don't just link me to a project), actual vs expected behavior, etc. Since I don't have contributing guidelines up yet, please Google for "how to file a good bug report" if you're new to this.

@araffin 

> If you don't want to integrate it in the crate, I would grateful if you could provide link/example to do it outside of the lib ;)

As I've already pointed out above, the underlying file descriptor and handle are exposed, so you can do anything you want with those. It's up to you to figure out what you need for your project, though. Sorry I can't help with that. My suggestion though is to use a short timeout.

**Pull request closed without merging**
